### ISSUE TITLE
composite functions do not work

### ISSUE THREAD

**Issue by goszlanyi** [filipesabella/CalcPad#20]
Dear @filipesabella.

While simple functions work just fine:
```
sqrt(2)
exp(1)
```
composite functions seem to fail completely:
```
sqrt(sqrt(2))
exp(exp(1))
```
Also there are more subtle cases of failure:
```
log(E)
sin(PI/2)
```
I think these are also composite functions, because they can be cured like this:
```
e=E
log(e)
pi=PI
sin(pi/2)
```

So I think composite functions are a real issue now.
- Do you know about this behavior?
- Is there any chance/interest that you can fix it?

Best regards, Gabor

**Comment by filipesabella** [comment]
Thank you for the detailed report, I've fixed the issue on the web version and will be releasing the desktop versions as I get a hold of a mac and windows machines.

**Comment by goszlanyi** [comment]
Thank you very much for the fix.
Unfortunately, part of the issue remains, the following code still fails:
```
log(E)
sin(PI/2)
```

**Comment by filipesabella** [comment]
Thanks again!

I started fixing for this case, but it's a losing battle given the really, really hacky implementation I did for this thing. It's all regular expressions.

For these two constants, if you use Math.PI and Math.E, it'll work.

```
log(Math.E);
sin(Math.PI/2);
```

**Comment by goszlanyi** [comment]
Thank you for your prompt feedback.
I can confirm that `Math.PI` and `Math.E` work,
and hope that at some point you can get `PI` and `E` working too.

**Comment by filipesabella** [comment]
That'll require a full rewrite to implement it as a language instead of parsing everything with regexes!
Maybe one day. Thanks again for the reports.
